name: meowblog
recipe: lamp
config:
  php: '8.1'
  webroot: webroot
  database: postgres
  services:
    cache:
      type: redis

proxy:
  appserver:
    - meowblog.lndo.site
    - "*.meowblog.lndo.site"
