version: "3.7"

networks:
  frontend:
    external: true
  cake_backend:
    internal: true

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    # image: ghcr.io/maymeow/cake-notify/cake-notify:latest
    env_file: .env
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    networks:
      - frontend
      - cake_backend
    depends_on:
      - redis
    volumes:
      - ./data:/data

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - cake_backend
      - frontend
    volumes_from:
      - app
    ports:
      - "8088:80"
    restart: unless-stopped
    depends_on:
      - app
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cake.rule=Host(`cake.domain.sk`)"
      - "traefik.http.routers.cake.entrypoints=web,websecure"
      - "traefik.http.routers.cake.tls.certresolver=le"
      - "traefik.http.routers.cake.tls.options=mytls@file"
      - "traefik.http.services.cake.loadbalancer.server.port=80"
      - "traefik.http.routers.cake.service=cake"
      - "traefik.docker.network=frontend"

  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - cake_backend

  # if you need graphic acces to application database
  # adminer:
  #   image: adminer
  #   networks:
  #     - frontend
  #   restart: unless-stopped
